In [1]:
import pandas as pd

In [8]:
data = pd.read_csv('NewComb2.csv')

In [9]:
data.head()

,Highest Layer,Transport Layer,Source IP,Dest IP,Source Port,Dest Port,Packet Length,Packets/Time,target
0,ARP,UDP,1,192.168.1.1,0,0,60,92.75,1
1,ARP,UDP,0,192.168.1.10,0,0,42,92.86,0
2,ARP,UDP,1,192.168.1.1,0,0,60,362.77,1
3,ARP,UDP,0,192.168.1.12,0,0,42,362.79,0
4,ARP,UDP,1,192.168.1.1,0,0,60,364.31,1

In [10]:
data = data.sample(frac=1).reset_index(drop=True)

In [11]:
data.head()

,Highest Layer,Transport Layer,Source IP,Dest IP,Source Port,Dest Port,Packet Length,Packets/Time,target
0,DATA,TCP,0,192.168.1.1,49158,5201,1514,249.56,0
1,ICMP,None,0,192.168.1.2,0,0,74,292.10,0
2,DATA,TCP,0,192.168.1.1,49158,5201,1514,289.44,0
3,QUIC,UDP,1,192.168.1.1,56187,80,60,467.79,1
4,QUIC,UDP,1,192.168.1.1,61636,80,60,479.57,1